
package py.com.fecyl.comunicasifen.wsdl.de;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "de-ws-sync-recibeService", targetNamespace = "http://ekuatia.set.gov.py/sifen/xsd", wsdlLocation = "https://sifen-test.set.gov.py/de/ws/sync/recibe.wsdl?wsdl")
public class DeWsSyncRecibeService
        extends Service {

    private final static URL DEWSSYNCRECIBESERVICE_WSDL_LOCATION;
    private final static WebServiceException DEWSSYNCRECIBESERVICE_EXCEPTION;
    private final static QName DEWSSYNCRECIBESERVICE_QNAME = new QName("http://ekuatia.set.gov.py/sifen/xsd", "de-ws-sync-recibeService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://sifen-test.set.gov.py/de/ws/sync/recibe.wsdl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DEWSSYNCRECIBESERVICE_WSDL_LOCATION = url;
        DEWSSYNCRECIBESERVICE_EXCEPTION = e;
    }

    public DeWsSyncRecibeService() {
        super(__getWsdlLocation(), DEWSSYNCRECIBESERVICE_QNAME);
    }

    public DeWsSyncRecibeService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DEWSSYNCRECIBESERVICE_QNAME, features);
    }

    public DeWsSyncRecibeService(URL wsdlLocation) {
        super(wsdlLocation, DEWSSYNCRECIBESERVICE_QNAME);
    }

    public DeWsSyncRecibeService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DEWSSYNCRECIBESERVICE_QNAME, features);
    }

    public DeWsSyncRecibeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DeWsSyncRecibeService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (DEWSSYNCRECIBESERVICE_EXCEPTION != null) {
            throw DEWSSYNCRECIBESERVICE_EXCEPTION;
        }
        return DEWSSYNCRECIBESERVICE_WSDL_LOCATION;
    }

    /**
     * @return returns DeWsSyncRecibe
     */
    @WebEndpoint(name = "de-ws-sync-recibeSoap12")
    public DeWsSyncRecibe getDeWsSyncRecibeSoap12() {
        return super.getPort(new QName("http://ekuatia.set.gov.py/sifen/xsd", "de-ws-sync-recibeSoap12"), DeWsSyncRecibe.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns DeWsSyncRecibe
     */
    @WebEndpoint(name = "de-ws-sync-recibeSoap12")
    public DeWsSyncRecibe getDeWsSyncRecibeSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://ekuatia.set.gov.py/sifen/xsd", "de-ws-sync-recibeSoap12"), DeWsSyncRecibe.class, features);
    }

}
