
package py.com.fecyl.comunicasifen.wsdl.de;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.math.BigInteger;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "de-ws-sync-recibe", targetNamespace = "http://ekuatia.set.gov.py/sifen/xsd")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface DeWsSyncRecibe {


    /**
     * @param xDE
     * @param dId
     * @return returns de.RProtDe
     */
    @WebMethod
    @WebResult(name = "rProtDe", targetNamespace = "http://ekuatia.set.gov.py/sifen/xsd")
    @RequestWrapper(localName = "rEnviDe", targetNamespace = "http://ekuatia.set.gov.py/sifen/xsd", className = "de.REnviDe")
    @ResponseWrapper(localName = "rRetEnviDe", targetNamespace = "http://ekuatia.set.gov.py/sifen/xsd", className = "de.RRetEnviDe")
    public RProtDe rEnviDe(
            @WebParam(name = "dId", targetNamespace = "http://ekuatia.set.gov.py/sifen/xsd")
                    BigInteger dId,
            @WebParam(name = "xDE", targetNamespace = "http://ekuatia.set.gov.py/sifen/xsd")
                    py.com.fecyl.comunicasifen.wsdl.de.REnviDe.XDE xDE);

}
