
package py.com.fecyl.comunicasifen.wsdl.evento;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "de-ws-eventos-eventoService", targetNamespace = "http://ekuatia.set.gov.py/sifen/xsd", wsdlLocation = "http://seguro.konecta.com.py:8191/sifen-ws-eventos/ws/evento.wsdl")
public class DeWsEventosEventoService
        extends Service {

    private final static URL DEWSEVENTOSEVENTOSERVICE_WSDL_LOCATION;
    private final static WebServiceException DEWSEVENTOSEVENTOSERVICE_EXCEPTION;
    private final static QName DEWSEVENTOSEVENTOSERVICE_QNAME = new QName("http://ekuatia.set.gov.py/sifen/xsd", "de-ws-eventos-eventoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://seguro.konecta.com.py:8191/sifen-ws-eventos/ws/evento.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DEWSEVENTOSEVENTOSERVICE_WSDL_LOCATION = url;
        DEWSEVENTOSEVENTOSERVICE_EXCEPTION = e;
    }

    public DeWsEventosEventoService() {
        super(__getWsdlLocation(), DEWSEVENTOSEVENTOSERVICE_QNAME);
    }

    public DeWsEventosEventoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DEWSEVENTOSEVENTOSERVICE_QNAME, features);
    }

    public DeWsEventosEventoService(URL wsdlLocation) {
        super(wsdlLocation, DEWSEVENTOSEVENTOSERVICE_QNAME);
    }

    public DeWsEventosEventoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DEWSEVENTOSEVENTOSERVICE_QNAME, features);
    }

    public DeWsEventosEventoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DeWsEventosEventoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (DEWSEVENTOSEVENTOSERVICE_EXCEPTION != null) {
            throw DEWSEVENTOSEVENTOSERVICE_EXCEPTION;
        }
        return DEWSEVENTOSEVENTOSERVICE_WSDL_LOCATION;
    }

    /**
     * @return returns DeWsEventosEvento
     */
    @WebEndpoint(name = "de-ws-eventos-eventoSoap12")
    public DeWsEventosEvento getDeWsEventosEventoSoap12() {
        return super.getPort(new QName("http://ekuatia.set.gov.py/sifen/xsd", "de-ws-eventos-eventoSoap12"), DeWsEventosEvento.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns DeWsEventosEvento
     */
    @WebEndpoint(name = "de-ws-eventos-eventoSoap12")
    public DeWsEventosEvento getDeWsEventosEventoSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://ekuatia.set.gov.py/sifen/xsd", "de-ws-eventos-eventoSoap12"), DeWsEventosEvento.class, features);
    }

}
