
package py.com.fecyl.comunicasifen.wsdl.consulta.ruc;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "de-ws-consultas-consulta-rucService", targetNamespace = "http://ekuatia.set.gov.py/sifen/xsd", wsdlLocation = "file:/C:/Users/luis.barboza/Documents/Coomecipar/consulta-ruc.wsdl")
public class DeWsConsultasConsultaRucService
    extends Service
{

    private final static URL DEWSCONSULTASCONSULTARUCSERVICE_WSDL_LOCATION;
    private final static WebServiceException DEWSCONSULTASCONSULTARUCSERVICE_EXCEPTION;
    private final static QName DEWSCONSULTASCONSULTARUCSERVICE_QNAME = new QName("http://ekuatia.set.gov.py/sifen/xsd", "de-ws-consultas-consulta-rucService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/luis.barboza/Documents/Coomecipar/consulta-ruc.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DEWSCONSULTASCONSULTARUCSERVICE_WSDL_LOCATION = url;
        DEWSCONSULTASCONSULTARUCSERVICE_EXCEPTION = e;
    }

    public DeWsConsultasConsultaRucService() {
        super(__getWsdlLocation(), DEWSCONSULTASCONSULTARUCSERVICE_QNAME);
    }

    public DeWsConsultasConsultaRucService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DEWSCONSULTASCONSULTARUCSERVICE_QNAME, features);
    }

    public DeWsConsultasConsultaRucService(URL wsdlLocation) {
        super(wsdlLocation, DEWSCONSULTASCONSULTARUCSERVICE_QNAME);
    }

    public DeWsConsultasConsultaRucService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DEWSCONSULTASCONSULTARUCSERVICE_QNAME, features);
    }

    public DeWsConsultasConsultaRucService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DeWsConsultasConsultaRucService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DeWsConsultasConsultaRuc
     */
    @WebEndpoint(name = "de-ws-consultas-consulta-rucSoap12")
    public DeWsConsultasConsultaRuc getDeWsConsultasConsultaRucSoap12() {
        return super.getPort(new QName("http://ekuatia.set.gov.py/sifen/xsd", "de-ws-consultas-consulta-rucSoap12"), DeWsConsultasConsultaRuc.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DeWsConsultasConsultaRuc
     */
    @WebEndpoint(name = "de-ws-consultas-consulta-rucSoap12")
    public DeWsConsultasConsultaRuc getDeWsConsultasConsultaRucSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://ekuatia.set.gov.py/sifen/xsd", "de-ws-consultas-consulta-rucSoap12"), DeWsConsultasConsultaRuc.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DEWSCONSULTASCONSULTARUCSERVICE_EXCEPTION!= null) {
            throw DEWSCONSULTASCONSULTARUCSERVICE_EXCEPTION;
        }
        return DEWSCONSULTASCONSULTARUCSERVICE_WSDL_LOCATION;
    }

}
