
package py.com.fecyl.comunicasifen.wsdl.consulta.ruc;

import java.math.BigInteger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "de-ws-consultas-consulta-ruc", targetNamespace = "http://ekuatia.set.gov.py/sifen/xsd")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DeWsConsultasConsultaRuc {


    /**
     * 
     * @param dCodRes
     * @param xContRUC
     * @param dMsgRes
     * @param dRUCCons
     * @param dId
     */
    @WebMethod
    @RequestWrapper(localName = "rEnviConsRUC", targetNamespace = "http://ekuatia.set.gov.py/sifen/xsd", className = "py.com.fecyl.fecylservice.wsdl.REnviConsRUC")
    @ResponseWrapper(localName = "rResEnviConsRUC", targetNamespace = "http://ekuatia.set.gov.py/sifen/xsd", className = "py.com.fecyl.fecylservice.wsdl.RResEnviConsRUC")
    public void rEnviConsRUC(
        @WebParam(name = "dId", targetNamespace = "http://ekuatia.set.gov.py/sifen/xsd")
        BigInteger dId,
        @WebParam(name = "dRUCCons", targetNamespace = "http://ekuatia.set.gov.py/sifen/xsd")
        String dRUCCons,
        @WebParam(name = "dCodRes", targetNamespace = "http://ekuatia.set.gov.py/sifen/xsd", mode = WebParam.Mode.OUT)
        Holder<String> dCodRes,
        @WebParam(name = "dMsgRes", targetNamespace = "http://ekuatia.set.gov.py/sifen/xsd", mode = WebParam.Mode.OUT)
        Holder<String> dMsgRes,
        @WebParam(name = "xContRUC", targetNamespace = "http://ekuatia.set.gov.py/sifen/xsd", mode = WebParam.Mode.OUT)
        Holder<TContenedorRuc> xContRUC);

}
