
package py.com.fecyl.comunicasifen.wsdl.lote;

import javax.activation.DataHandler;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.math.BigInteger;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "de-ws-async-recibe", targetNamespace = "http://ekuatia.set.gov.py/sifen/xsd")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface DeWsAsyncRecibe {


    /**
     * @param dCodRes
     * @param dProtConsLote
     * @param xDE
     * @param dTpoProces
     * @param dFecProc
     * @param dMsgRes
     * @param dId
     */
    @WebMethod
    @RequestWrapper(localName = "rEnvioLote", targetNamespace = "http://ekuatia.set.gov.py/sifen/xsd", className = "lote.REnvioLote")
    @ResponseWrapper(localName = "rResEnviLoteDe", targetNamespace = "http://ekuatia.set.gov.py/sifen/xsd", className = "lote.RResEnviLoteDe")
    public void rEnvioLote(
            @WebParam(name = "dId", targetNamespace = "http://ekuatia.set.gov.py/sifen/xsd")
                    BigInteger dId,
            @WebParam(name = "xDE", targetNamespace = "http://ekuatia.set.gov.py/sifen/xsd")
                    DataHandler xDE,
            @WebParam(name = "dFecProc", targetNamespace = "http://ekuatia.set.gov.py/sifen/xsd", mode = WebParam.Mode.OUT)
                    Holder<XMLGregorianCalendar> dFecProc,
            @WebParam(name = "dCodRes", targetNamespace = "http://ekuatia.set.gov.py/sifen/xsd", mode = WebParam.Mode.OUT)
                    Holder<String> dCodRes,
            @WebParam(name = "dMsgRes", targetNamespace = "http://ekuatia.set.gov.py/sifen/xsd", mode = WebParam.Mode.OUT)
                    Holder<String> dMsgRes,
            @WebParam(name = "dProtConsLote", targetNamespace = "http://ekuatia.set.gov.py/sifen/xsd", mode = WebParam.Mode.OUT)
                    Holder<Long> dProtConsLote,
            @WebParam(name = "dTpoProces", targetNamespace = "http://ekuatia.set.gov.py/sifen/xsd", mode = WebParam.Mode.OUT)
                    Holder<BigInteger> dTpoProces);

}
