
package py.com.fecyl.comunicasifen.wsdl.lote;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "de-ws-async-recibeService", targetNamespace = "http://ekuatia.set.gov.py/sifen/xsd", wsdlLocation = "https://sifen-test.set.gov.py/de/ws/async/recibe-lote.wsdl?wsdl")
public class DeWsAsyncRecibeService
        extends Service {

    private final static URL DEWSASYNCRECIBESERVICE_WSDL_LOCATION;
    private final static WebServiceException DEWSASYNCRECIBESERVICE_EXCEPTION;
    private final static QName DEWSASYNCRECIBESERVICE_QNAME = new QName("http://ekuatia.set.gov.py/sifen/xsd", "de-ws-async-recibeService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://sifen-test.set.gov.py/de/ws/async/recibe-lote.wsdl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DEWSASYNCRECIBESERVICE_WSDL_LOCATION = url;
        DEWSASYNCRECIBESERVICE_EXCEPTION = e;
    }

    public DeWsAsyncRecibeService() {
        super(__getWsdlLocation(), DEWSASYNCRECIBESERVICE_QNAME);
    }

    public DeWsAsyncRecibeService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DEWSASYNCRECIBESERVICE_QNAME, features);
    }

    public DeWsAsyncRecibeService(URL wsdlLocation) {
        super(wsdlLocation, DEWSASYNCRECIBESERVICE_QNAME);
    }

    public DeWsAsyncRecibeService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DEWSASYNCRECIBESERVICE_QNAME, features);
    }

    public DeWsAsyncRecibeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DeWsAsyncRecibeService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (DEWSASYNCRECIBESERVICE_EXCEPTION != null) {
            throw DEWSASYNCRECIBESERVICE_EXCEPTION;
        }
        return DEWSASYNCRECIBESERVICE_WSDL_LOCATION;
    }

    /**
     * @return returns DeWsAsyncRecibe
     */
    @WebEndpoint(name = "de-ws-async-recibeSoap12")
    public DeWsAsyncRecibe getDeWsAsyncRecibeSoap12() {
        return super.getPort(new QName("http://ekuatia.set.gov.py/sifen/xsd", "de-ws-async-recibeSoap12"), DeWsAsyncRecibe.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns DeWsAsyncRecibe
     */
    @WebEndpoint(name = "de-ws-async-recibeSoap12")
    public DeWsAsyncRecibe getDeWsAsyncRecibeSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://ekuatia.set.gov.py/sifen/xsd", "de-ws-async-recibeSoap12"), DeWsAsyncRecibe.class, features);
    }

}
